apiVersion: v1
kind:  Service
metadata:
  name: mgt-frontend-prod-service
  namespace: prod-env
  labels:
    app: mgt-frontend
    env: prod
spec:
  selector:
    app: mgt-frontend
    env: prod
  ports:
    - port: 80
      targetPort: 8303
  type: NodePort
