apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-frontend-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pavan05000/testing-app.git
    targetRevision: HEAD
    path: env/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

