apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt-frontend-test-deploy
  namespace: test-env
  labels:
    app: mgt-frontend
    env: test
spec:
 replicas: 2
 selector:
   matchLabels:
     app: mgt-frontend
     env: test
 template:
    metadata:
      labels:
        app: mgt-frontend
        env: test
    spec:
      containers:
        - name: angular-pmo-container
          image: pavan050/project-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8301
          livenessProbe:  #is the app is dead or running
            # If the app is dead, it will be restarted by the kubelet
            httpGet:
              path: /
              port: 8301
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:  # is the app ready to receive traffic
            httpGet:
              path: /
              port: 8301
            initialDelaySeconds: 0
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
