apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt-frontend-test-deploy
  namespace: test-env
  labels:
    app: mgt-frontend
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mgt-frontend
      env: test
  template:
    metadata:
      labels:
        app: mgt-frontend
        env: test
    spec:
      containers:
        - name: angular-pmo-container
          image: pavan050/project-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8301
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

