apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-fe
  template:
    metadata:
      labels:
        app: test-fe
    spec:
      containers:
      - name: your-app
        image: pavan050/fe-app:latest
        ports:
        - containerPort: 8301

