apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-fe
  template:
    metadata:
      labels:
        app: test-fe
    spec:
      containers:
      - name: your-app
        image: pavan050/fe-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8301
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

