apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: NodePort
  selector:
    app: test-fe
  ports:
    - protocol: TCP
      port: 8301
      targetPort: 8301
      nodePort: 30001
